# Simple layout configuration manifest
# Most states use scatter plots, a few use different chart types

defaults:
  chart_type: "scatter_plot"
  num_plots: 300

overrides:
  # States with different chart types
  CA:
    chart_type: "bar_chart"
  
  TX:
    chart_type: "bar_chart"
  
  NY:
    chart_type: "bar_chart"
  
  FL:
    chart_type: "line_chart"
  
  IL:
    chart_type: "heatmap"